<?php

namespace Adlino\IranGeo\Database\Seeds;

use Adlino\IranGeo\Models\City;
use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
	    City::insert([
            [
                'province_id' => 8,
                'county_id' => 98,
                'name' => 'اسلامشهر',
                'en_name' => 'Eslamshahr',
                'latitude' => '35.5826021',
                'longitude' => '51.1218216',
            ],
            [
			    'province_id' => 8,
			    'county_id' => 98,
			    'name' => 'احمدآباد مستوفی',
			    'en_name' => 'Ahmadabad-E Mostowfi',
			    'latitude' => '35.6351851',
			    'longitude' => '51.203692',
		    ],
		    [
			    'province_id' => 8,
			    'county_id' => 98,
			    'name' => 'چهاردانگه',
			    'en_name' => 'Chahar Dangeh',
			    'latitude' => '35.596159 ',
			    'longitude' => '51.315565',
		    ],
            [
                'province_id' => 8,
                'county_id' => 99,
                'name' => 'نسيم شهر',
                'en_name' => 'Nasimshahr',
                'latitude' => '35.5638588',
                'longitude' => '51.1396836',
            ],
            [
                'province_id' => 8,
                'county_id' => 99,
                'name' => 'نصیر شهر',
                'en_name' => 'Nasirshahr',
                'latitude' => '35.4903291',
                'longitude' => '51.1323023',
            ],
		    [
			    'province_id' => 8,
			    'county_id' => 99,
			    'name' => 'صالحيه',
			    'en_name' => 'salehie',
			    'latitude' => '35.5999212',
			    'longitude' => '51.2827227',
		    ],
		    [
			    'province_id' => 8,
			    'county_id' => 99,
			    'name' => 'گلستان',
			    'en_name' => 'Golestan',
			    'latitude' => '35.5207449',
			    'longitude' => '51.170175',
		    ],
		    [
			    'province_id' => 8,
			    'county_id' => 100,
			    'name' => 'پاکدشت',
			    'en_name' => 'Pakdasht',
			    'latitude' => '35.4449805',
			    'longitude' => '51.6195967',
		    ],
		    [
			    'province_id' => 8,
			    'county_id' => 100,
			    'name' => 'شريف آباد',
			    'en_name' => 'Sharifabad',
			    'latitude' => '35.4273131',
			    'longitude' => '51.768608',
		    ],
            [
                'province_id' => 8,
                'county_id' => 101,
                'name' => 'پرديس',
                'en_name' => 'Pardis',
                'latitude' => '35.741701',
                'longitude' => '51.780801',
            ],
		    [
			    'province_id' => 8,
			    'county_id' => 101,
			    'name' => 'بومهن',
			    'en_name' => 'Bumehen',
			    'latitude' => '35.733646',
			    'longitude' => '51.868124',
		    ],
		    [
			    'province_id' => 8,
			    'county_id' => 102,
			    'name' => 'پيشوا',
			    'en_name' => 'Pishva',
			    'latitude' => '35.307785',
			    'longitude' => '51.730872',
		    ],
		    [
			    'province_id' => 8,
			    'county_id' => 103,
			    'name' => 'تهران',
			    'en_name' => 'Tehran',
			    'latitude' => '35.689198 ',
			    'longitude' => '51.388974',
		    ],
            [
                'province_id' => 8,
                'county_id' => 104,
                'name' => 'دماوند',
                'en_name' => 'Damavand',
                'latitude' => '35.7086615',
                'longitude' => '52.0100624',
            ],
		    [
			    'province_id' => 8,
			    'county_id' => 104,
			    'name' => 'آبسرد',
			    'en_name' => 'Absard',
			    'latitude' => '35.6293144',
			    'longitude' => '52.1340745',
		    ],
            [
                'province_id' => 8,
                'county_id' => 104,
                'name' => 'کيلان',
                'en_name' => 'Kilan',
                'latitude' => '35.5526704',
                'longitude' => '52.1162218',
            ],
            [
                'province_id' => 8,
                'county_id' => 104,
                'name' => 'رودهن',
                'en_name' => 'Rudehen',
                'latitude' => '35.7338129',
                'longitude' => '51.8981265',
            ],
		    [
			    'province_id' => 8,
			    'county_id' => 104,
			    'name' => 'آبعلي',
			    'en_name' => 'Abali',
			    'latitude' => '35.767596',
			    'longitude' => '51.9412993',
		    ],
		    [
			    'province_id' => 8,
			    'county_id' => 105,
			    'name' => 'رباط‌کریم',
			    'en_name' => 'Robat Karim',
			    'latitude' => '35.4752344',
			    'longitude' => '51.0473293',
		    ],
            [
                'province_id' => 8,
                'county_id' => 106,
                'name' => 'شهرري',
                'en_name' => 'Shahr-e-Rey',
                'latitude' => '35.5725813',
                'longitude' => '51.4233648',
            ],
            [
                'province_id' => 8,
                'county_id' => 106,
                'name' => 'حسن آباد',
                'en_name' => 'Hasanabad',
                'latitude' => '35.3695228',
                'longitude' => '51.2215231',
            ],
            [
                'province_id' => 8,
                'county_id' => 106,
                'name' => 'کهريزک',
                'en_name' => 'Kahrizak',
                'latitude' => '35.5168394',
                'longitude' => '51.3507842',
            ],
		    [
			    'province_id' => 8,
			    'county_id' => 106,
			    'name' => 'باقرشهر',
			    'en_name' => 'Baghershahr',
			    'latitude' => '35.5335618',
			    'longitude' => '51.3954691',
		    ],
		    [
			    'province_id' => 8,
			    'county_id' => 107,
			    'name' => 'تجريش',
			    'en_name' => 'Tajrish',
			    'latitude' => '35.8046493',
			    'longitude' => '51.4313206',
		    ],
            [
                'province_id' => 8,
                'county_id' => 107,
                'name' => 'لواسان',
                'en_name' => 'Lavasan',
                'latitude' => '35.8232502',
                'longitude' => '51.60526',
            ],
            [
                'province_id' => 8,
                'county_id' => 107,
                'name' => 'فشم',
                'en_name' => 'Fasham',
                'latitude' => '35.9317215',
                'longitude' => '51.511309',
            ],
		    [
			    'province_id' => 8,
			    'county_id' => 107,
			    'name' => 'شمشک',
			    'en_name' => 'Shemshak',
			    'latitude' => '36.0112867',
			    'longitude' => '51.486547',
		    ],
            [
                'province_id' => 8,
                'county_id' => 108,
                'name' => 'شهريار',
                'en_name' => 'Shahriar',
                'latitude' => '35.6591813',
                'longitude' => '51.0068091',
            ],
		    [
			    'province_id' => 8,
			    'county_id' => 108,
			    'name' => 'انديشه',
			    'en_name' => 'Andisheh',
			    'latitude' => '35.7468945',
			    'longitude' => '51.2690735',
		    ],
		    [
			    'province_id' => 8,
			    'county_id' => 108,
			    'name' => 'باغستان',
			    'en_name' => 'Baghestan',
			    'latitude' => '35.6424709',
			    'longitude' => '51.0802008',
		    ],
            [
                'province_id' => 8,
                'county_id' => 108,
                'name' => 'فردوسيه',
                'en_name' => 'Ferdosiye',
                'latitude' => '35.5972932',
                'longitude' => '51.0240263',
            ],
            [
                'province_id' => 8,
                'county_id' => 108,
                'name' => 'صباشهر',
                'en_name' => 'Sabashahr',
                'latitude' => '35.5832376',
                'longitude' => '51.0814684',
            ],
		    [
			    'province_id' => 8,
			    'county_id' => 108,
			    'name' => 'شاهدشهر',
			    'en_name' => 'Shahedshahr',
			    'latitude' => '35.5726924',
			    'longitude' => '51.0788298',
		    ],
		    [
			    'province_id' => 8,
			    'county_id' => 108,
			    'name' => 'وحيديه',
			    'en_name' => 'Vahidieh',
			    'latitude' => '35.6048346',
			    'longitude' => '51.0162591',
		    ],
            [
                'province_id' => 8,
                'county_id' => 109,
                'name' => 'فيروزکوه',
                'en_name' => 'Firuzkuh',
                'latitude' => '35.7570281',
                'longitude' => '52.7556218',
            ],
		    [
			    'province_id' => 8,
			    'county_id' => 109,
			    'name' => 'ارجمند',
			    'en_name' => 'Arjmand',
			    'latitude' => '35.8140017',
			    'longitude' => '52.5035333',
		    ],
		    [
			    'province_id' => 8,
			    'county_id' => 110,
			    'name' => 'قدس',
			    'en_name' => 'Qods',
			    'latitude' => '35.7106874',
			    'longitude' => '51.0791081',
		    ],
		    [
			    'province_id' => 8,
			    'county_id' => 111,
			    'name' => 'قرچک',
			    'en_name' => 'Qarchak',
			    'latitude' => '35.437052',
			    'longitude' => '51.5580653',
		    ],
            [
                'province_id' => 8,
                'county_id' => 112,
                'name' => 'ملارد',
                'en_name' => 'Malard',
                'latitude' => '35.6794086',
                'longitude' => '50.9456843',
            ],
		    [
			    'province_id' => 8,
			    'county_id' => 112,
			    'name' => 'صفادشت',
			    'en_name' => 'Safadasht',
			    'latitude' => '35.684489',
			    'longitude' => '50.824658',
		    ],
            [
                'province_id' => 8,
                'county_id' => 113,
                'name' => 'ورامين',
                'en_name' => 'Varamin',
                'latitude' => '35.3448727',
                'longitude' => '51.6078465',
            ],
		    [
			    'province_id' => 8,
			    'county_id' => 113,
			    'name' => 'جوادآباد',
			    'en_name' => 'Javadabad',
			    'latitude' => '35.2102001',
			    'longitude' => '51.6727752',
		    ],
	    ]);
    }
}
